#!/bin/sh
pgrep redshift || redshift &

~/.config/conky/start-conky.sh &
firefox --class="init_firefox" &

# https://github.com/adi1090x/dynamic-wallpaper
# Autostart the wallpaper
dwall -s mountains &
